print("*****************************************")
print("*\t\t\t\t\t*")
print("*\tWelcome to the JARVIS Prompt\t*")
print("*\t\t\t\t\t*")
print("*****************************************")
print("\nHello my name is JARVIS!")
name=input('What is your name?\n')
print("Hello.........!"+" "+name)
